version: '3'

services:
  pepenode0:
    container_name: pepenode0
    image: "pepenode:latest"
    ports:
      - "26656-26657:26656-26657"
      - "1317:1317"
      - "8545-8546:8545-8546"
    volumes:
      - ./build/pepenode0/:/opt/build/pepe_home/
    command: bash ${COMMAND}.sh pepenode0
    environment:
      - TZ=Asia/Bangkok
    networks:
      localnet:
        ipv4_address: 192.167.10.2

  pepenode1:
    container_name: pepenode1
    image: "pepenode:latest"
    ports:
      - "26659-26660:26656-26657"
      - "8547-8548:8545-8546"
    volumes:
      - ./build/pepenode1/:/opt/build/pepe_home/
    command: bash ${COMMAND}.sh pepenode1
    environment:
      - TZ=Asia/Soul
    networks:
      localnet:
        ipv4_address: 192.167.10.3

  pepenode2:
    container_name: pepenode2
    image: "pepenode:latest"
    ports:
      - "26661-26662:26656-26657"
      - "8549-8550:8545-8546"
    volumes:
      - ./build/pepenode2/:/opt/build/pepe_home/
    command: bash ${COMMAND}.sh pepenode2
    environment:
      - TZ=America/New_York
    networks:
      localnet:
        ipv4_address: 192.167.10.4

  pepenode3:
    container_name: pepenode3
    image: "pepenode:latest"
    ports:
      - "26663-26664:26656-26657"
      - "8551-8552:8545-8546"
    volumes:
      - ./build/pepenode3/:/opt/build/pepe_home/
    command: bash ${COMMAND}.sh pepenode3
    environment:
      - TZ=Europe/London
    networks:
      localnet:
        ipv4_address: 192.167.10.5

networks:
  localnet:
    driver: bridge
    ipam:
      driver: default
      config:
        -
          subnet: 192.167.10.0/16